/**
 * @file Manages dynamic resources generated by the user (documents, images, etc.) stored in /dynamic_storage.
 * Allows listing, reading, writing, deleting, getting metadata, and searching for resources.
 * @author David Jurado
 * @date 2025-05-04
 * @copyright Copyright (c) 2025 David Jurado
 * @license MIT
 */
import { z } from 'zod';
import * as fs from 'fs-extra';
import path from 'path';
import NodeCache from 'node-cache';
import { McpResource, ApiResponse, ToolRequestParams, FastMCPContext } from '@/types/common.types';
import logger from '@/utils/logger'; // Import logger

// Base directory for storing dynamic resources
const DYNAMIC_STORAGE_DIR = path.join(__dirname, '..', '..', '..', 'dynamic_storage');

// Configuration options for the resource system
const RESOURCE_SYSTEM_ENABLED = process.env.RESOURCE_SYSTEM_ENABLED !== 'false'; // Enabled by default
const RESOURCE_LIMIT_PER_TYPE = process.env.RESOURCE_LIMIT_PER_TYPE ? parseInt(process.env.RESOURCE_LIMIT_PER_TYPE, 10) : undefined; // Limit per resource type
const RESOURCE_LIMIT_TOTAL = process.env.RESOURCE_LIMIT_TOTAL ? parseInt(process.env.RESOURCE_LIMIT_TOTAL, 10) : undefined; // Total limit

// Virtual directory structure: <tool_name>/<YYYY-MM-DD>/<filename>
const getOrganizedResourcePath = (toolName: string, filename: string): string => {
  const today = new Date();
  const datePath = today.toISOString().split('T')[0]; // YYYY-MM-DD
  const resourceRelativePath = path.join(toolName, datePath, filename);
  return path.join(DYNAMIC_STORAGE_DIR, resourceRelativePath);
};

// Initialize cache for metadata (optional, for performance improvement)
const metadataCache = new NodeCache({ stdTTL: 600, checkperiod: 120 }); // Cache for 10 minutes

/**
 * @tool dynamic/resources
 * @description Manages dynamic resources generated by the user (documents, images, etc.) stored in /dynamic_storage.
 * Allows listing, reading, writing, deleting, getting metadata, and searching for resources.
 */

// Input schema for resource operations
// Combined schema for all operations (using z.object)
const DynamicResourcesInputSchema = z.object({
    operation: z.enum(['list', 'read', 'write', 'delete', 'metadata', 'search']).describe('The operation to perform (list, read, write, delete, metadata, or search).'),
    // Include all possible fields for the operations
    resourceId: z.string().optional().describe("(read, delete, metadata) Unique ID of the resource."), // Make optional here, validate in handler
    filePath: z.string().optional().describe("(read, write, delete, metadata) Relative path within dynamic_storage. Required for read, write, delete, metadata."), // Make optional here, validate in handler
    content: z.string().optional().describe("(write) Content of the resource. Required for write."), // Make optional here, validate in handler
    type: z.string().optional().describe("(list, search) Filter by resource type (e.g., 'document', 'image')."),
    query: z.string().optional().describe("(list, search) Search query (for the 'search' operation). Required for search."), // Make optional here, validate in handler
}).refine(data => {
    // Conditional validations based on the operation
    if (data.operation === 'read' || data.operation === 'delete' || data.operation === 'metadata') {
        return data.resourceId !== undefined || data.filePath !== undefined; // Requires resourceId or filePath
    } else if (data.operation === 'write') {
        return data.filePath !== undefined && data.content !== undefined; // Requires filePath and content
    } else if (data.operation === 'search') {
        return data.query !== undefined; // Requires query
    }
    // 'list' does not require additional fields
    return true; // Passes validation if the operation does not require specific fields or if it has them
}, {
    message: "Missing required fields for the specified operation.",
    path: [], // Apply error to the whole object
});


// Infer the combined type for use in the handler
type DynamicResourcesInput = z.infer<typeof DynamicResourcesInputSchema>;


// Function to get the full path of a resource from its relative path within dynamic_storage
const getFullPathFromRelative = (relativePath: string): string => {
  const fullPath = path.join(DYNAMIC_STORAGE_DIR, relativePath);
  // Ensure the path is within the dynamic storage directory
  // This is a crucial security validation
  if (!fullPath.startsWith(DYNAMIC_STORAGE_DIR)) {
    throw new Error('Access denied: resource path is outside the allowed storage directory.');
  }
  return fullPath;
};

// Function to save a resource with the organized structure
const saveResource = async (toolName: string, filename: string, content: string | Buffer): Promise<string> => {
  if (!RESOURCE_SYSTEM_ENABLED) {
    logger.info('[dynamic/resources] Resource system is disabled. Skipping save.');
    return ''; // Return empty string or similar if disabled
  }

  const fullPath = getOrganizedResourcePath(toolName, filename);
  await fs.ensureDir(path.dirname(fullPath)); // Ensure the parent directory exists
  await fs.writeFile(fullPath, content); // Use writeFile which handles strings and Buffers

  // Implement limit logic here if necessary
  // This could be complex (list all files, sort by date, delete the oldest)
  // For now, we just save. Limit logic can be added later.

  // Return the relative path within dynamic_storage
  return path.relative(DYNAMIC_STORAGE_DIR, fullPath);
};

// Function to delete old resources based on configured limits
const enforceResourceLimits = async () => {
  if (!RESOURCE_SYSTEM_ENABLED || (!RESOURCE_LIMIT_PER_TYPE && !RESOURCE_LIMIT_TOTAL)) {
    return; // Do nothing if the system is disabled or no limits are configured
  }

  logger.info('[dynamic/resources] Enforcing resource limits...');

  // Limit implementation (simplified for now)
  // This would require listing all files, grouping by type/tool,
  // sorting by modification date and deleting the excess.
  // Given the complexity, this part is left as a TODO for a more robust future implementation.
  logger.warn('[dynamic/resources] Resource limit enforcement is not fully implemented yet.');
};

// Implementation of the resource handler
const handler = async (params: ToolRequestParams, context?: FastMCPContext<any>): Promise<ApiResponse<any>> => {
  const log = context?.log || logger; // Use the context logger if available, otherwise the global one

  let validatedRequest: DynamicResourcesInput;
  try {
    // Validate input parameters using the new schema
    validatedRequest = DynamicResourcesInputSchema.parse(params);
  } catch (error: any) {
     // If initial validation fails, return a validation error
     if (error instanceof z.ZodError) {
         // Serialize error.errors to be serializable
         const errorDetails = JSON.stringify(error.errors, null, 2);
         log.warn(`[dynamic/resources] Input validation failed: ${error.message}`, { errors: errorDetails, params });
         return {
             success: false,
             error: {
                 code: 'VALIDATION_ERROR',
                 message: 'Input validation error.',
                 details: errorDetails,
             },
         };
     }
     // Another unexpected error during initial parsing
     log.error(`[dynamic/resources] Unexpected error parsing params: ${error.message}`, { error: String(error), params });
     return {
         success: false,
         error: {
             code: 'INTERNAL_ERROR',
             message: 'Failed to parse tool parameters.',
             details: String(error),
         },
     };
  }

  const { operation, ...args } = validatedRequest; // Extract operation and the rest as args
  const { resourceId, filePath, content, type, query } = args; // Extract specific fields

  try {
    // Ensure the storage directory exists
    await fs.ensureDir(DYNAMIC_STORAGE_DIR);

    switch (operation) {
      case 'list': {
        // List resources recursively to reflect the organized structure
        const listFilesRecursively = async (dir: string, relativeDir = ''): Promise<any[]> => {
          const entries = await fs.readdir(dir, { withFileTypes: true });
          let resources: any[] = [];

          for (const entry of entries) {
            const fullPath = path.join(dir, entry.name);
            const relativePath = path.join(relativeDir, entry.name);
            const stats = await fs.stat(fullPath);

            if (entry.isDirectory()) {
              // If it's a directory, list recursively
              resources.push({
                id: relativePath,
                name: entry.name,
                type: 'directory',
                filePath: relativePath,
                createdAt: stats.birthtime,
                updatedAt: stats.mtime,
                size: stats.size, // Directory size may not be accurate
              });
              resources = resources.concat(await listFilesRecursively(fullPath, relativePath));
            } else {
              // If it's a file
              resources.push({
                id: relativePath,
                name: entry.name,
                type: 'file',
                filePath: relativePath,
                createdAt: stats.birthtime,
                updatedAt: stats.mtime,
                size: stats.size,
              });
            }
          }
          return resources;
        };

        const allResources = await listFilesRecursively(DYNAMIC_STORAGE_DIR);
        // Filter by type if specified
        const filteredResources = type ? allResources.filter(res => res.type === type) : allResources;

        return { success: true, data: filteredResources };
      }

      case 'read': {
        // Validate that filePath or resourceId was provided (already done in refine)
        const targetPath = filePath ? getFullPathFromRelative(filePath) : (resourceId ? getFullPathFromRelative(resourceId) : undefined);
        if (!targetPath) throw new Error("filePath or resourceId is required for 'read' operation.");

        if (!await fs.pathExists(targetPath)) {
          return { success: false, error: { code: 'NOT_FOUND', message: `Resource not found: ${filePath || resourceId}` } };
        }
        const content = await fs.readFile(targetPath, 'utf-8');
        return { success: true, data: { content } };
      }

      case 'write': {
        // This operation will now be used internally by other tools via saveResource
        // It should not be called directly by the client with this logic.
        // We could keep it for flexibility, but the organization and limit logic
        // should go through saveResource.
        // For now, we leave it as it was, but with full path validation.
         if (!filePath || content === undefined) throw new Error("filePath and content are required for 'write' operation.");
         const fullPath = getFullPathFromRelative(filePath);
         await fs.ensureDir(path.dirname(fullPath));
         await fs.writeFile(fullPath, content, 'utf-8');
         metadataCache.del(filePath);
         // After writing, apply limits
         await enforceResourceLimits();
         return { success: true, data: { filePath: filePath } };
      }

      case 'delete': {
        // Validate that filePath or resourceId was provided (already done in refine)
        const targetPath = filePath ? getFullPathFromRelative(filePath) : (resourceId ? getFullPathFromRelative(resourceId) : undefined);
        if (!targetPath) throw new Error("filePath or resourceId is required for 'delete' operation.");

         if (!await fs.pathExists(targetPath)) {
          return { success: false, error: { code: 'NOT_FOUND', message: `Resource not found: ${filePath || resourceId}` } };
        }
        await fs.remove(targetPath);
        // Invalidate cache for this resource
        const cacheKey = filePath || resourceId;
        if (cacheKey) metadataCache.del(cacheKey); // Invalidate using filePath or resourceId
        // After deleting, apply limits (this might be redundant if the deletion was manual)
        await enforceResourceLimits();
        return { success: true, data: { filePath: filePath || resourceId } };
      }

      case 'metadata': {
        // Validate that filePath or resourceId was provided (already done in refine)
        const targetPath = filePath ? getFullPathFromRelative(filePath) : (resourceId ? getFullPathFromRelative(resourceId) : undefined);
        if (!targetPath) throw new Error("filePath or resourceId is required for 'metadata' operation.");

        const cacheKey = filePath || resourceId; // Use filePath or resourceId as cache key
        if (cacheKey) { // Only attempt to get from cache if the key is defined
            const cachedMetadata = metadataCache.get(cacheKey);
            if (cachedMetadata) {
              return { success: true, data: cachedMetadata };
            }
        }

        if (!await fs.pathExists(targetPath)) {
          return { success: false, error: { code: 'NOT_FOUND', message: `Resource not found: ${filePath || resourceId}` } };
        }
        const stats = await fs.stat(targetPath);
        const metadata = {
          id: filePath || resourceId, // Use relative path or resourceId as ID
          name: path.basename(targetPath),
          type: stats.isDirectory() ? 'directory' : 'file',
          createdAt: stats.birthtime,
          updatedAt: stats.mtime,
          size: stats.size,
          filePath: filePath || resourceId, // Use relative path or resourceId
          // More metadata could be added here if needed (e.g., hash, permissions, etc.)
        };
        if (cacheKey) metadataCache.set(cacheKey, metadata); // Only set in cache if the key is defined
        return { success: true, data: metadata };
      }

      case 'search': {
        // Validate that query is not undefined (already done in refine)
        if (!query) throw new Error("query is required for 'search' operation.");

        // Basic search implementation: search for files containing the query in their name
        // A more advanced implementation could index content or use dedicated search tools
        // To search in the organized structure, we need to list recursively first
        const listFilesRecursively = async (dir: string, relativeDir = ''): Promise<string[]> => {
            const entries = await fs.readdir(dir, { withFileTypes: true });
            let filePaths: string[] = [];

            for (const entry of entries) {
                const fullPath = path.join(dir, entry.name);
                const relativePath = path.join(relativeDir, entry.name);

                if (entry.isDirectory()) {
                    filePaths = filePaths.concat(await listFilesRecursively(fullPath, relativePath));
                } else {
                    filePaths.push(relativePath);
                }
            }
            return filePaths;
        };

        const allRelativePaths = await listFilesRecursively(DYNAMIC_STORAGE_DIR);
        const matchingRelativePaths = allRelativePaths.filter(relativePath => relativePath.includes(query!));

        const resources = await Promise.all(matchingRelativePaths.map(async (relativePath) => {
           const fullPath = getFullPathFromRelative(relativePath);
           const stats = await fs.stat(fullPath);
           return {
             id: relativePath,
             name: path.basename(relativePath),
             type: 'file', // Assume search is only on files for now
             createdAt: stats.birthtime,
             updatedAt: stats.mtime,
             size: stats.size,
             filePath: relativePath,
           };
         }));
        // Optional: filter by type if specified (although current search is only on file names)
        const filteredResources = type ? resources.filter(res => res.type === type) : resources;


        return { success: true, data: filteredResources };
      }

      default:
        // This should not happen thanks to discriminatedUnion, but it's a safe fallback
        // const exhaustiveCheck: never = operation; // No longer needed with combined schema
        throw new Error(`Unsupported operation: ${operation}`); // Access operation directly
    }
  } catch (error: any) {
    const message = error instanceof Error ? error.message : String(error);
    log.error(`[dynamic/resources] Error in tool: ${message}`, { error: String(error), params }); // Serialize error
    return { success: false, error: { code: 'TOOL_EXECUTION_ERROR', message: `Error in dynamic/resources tool: ${message}`, details: String(error) } }; // Return ErrorResponse
  }
};

// Export the saveResource function so other tools can use it
export { saveResource };

// Definition of the McpResource tool
export const dynamicResourcesTool: McpResource[] = [{
  path: 'dynamic/resources',
  description: 'Manages dynamic resources generated by the user (documents, images, etc.) stored in /dynamic_storage. Allows listing, reading, writing, deleting, getting metadata, and searching for resources.', // Translated description
  handler: handler,
  schema: DynamicResourcesInputSchema, // Use the new z.object schema
}];